name: build

on:
  push:
    branches-ignore:
    - 'refs/tags/*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install FlubuCore
      run: dotnet tool install --global FlubuCore.Tool
    - name: 默认构建
      run: flubu build

