name: build

on:
  push:
    branches:
    - main
    - develop
    - release/*
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install FlubuCore
      run: dotnet tool install --global FlubuCore.GlobalTool
    - name: 默认构建
      run: flubu build
